### ISSUE TITLE
Pineapple growth without the Serene Seasons mod causes the server to crash.

### ISSUE THREAD

**Issue by hanbings** [AmarokIce/PineappleDelight#13]
logs summary:

```java
[18:11:07 ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Exception ticking world
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServerMixin.java:897) ~[server-1.20.1-20230612.114412-srg.jar%23251!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServerMixin.java:283) ~[server-1.20.1-20230612.114412-srg.jar%23251!/:?]
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServerMixin.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23251!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2070) ~[server-1.20.1-20230612.114412-srg.jar%23251!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23251!/:?]
        at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because "club.someoneice.pineapple.PineappleMain.SEASON_INSTALL" is null
        at club.someoneice.pineapple.common.PineappleCrop.m_213898_(PineappleCrop.java:27) ~[【农夫乐事：凤梨乐事】PineappleDelight-Forge-1.20-1.0.8.jar%23216!/:1.0.8]
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_222972_(BlockBehaviour_BlockStateBaseMixin.java:762) ~[server-1.20.1-20230612.114412-srg.jar%23251!/:?]
        at net.minecraft.server.level.ServerLevel.m_8714_(ServerLevelMixin.java:481) ~[server-1.20.1-20230612.114412-srg.jar%23251!/:?]
        at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCacheMixin.java:362) ~[server-1.20.1-20230612.114412-srg.jar%23251!/:?]
        at net.minecraft.server.level.ServerChunkCache.m_201698_(ServerChunkCacheMixin.java:312) ~[server-1.20.1-20230612.114412-srg.jar%23251!/:?]
        at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevelMixin.java:305) ~[server-1.20.1-20230612.114412-srg.jar%23251!/:?]
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServerMixin.java:893) ~[server-1.20.1-20230612.114412-srg.jar%23251!/:?]
        ... 5 more
```

[crash-2024-03-03_18.11.07-server.txt](https://github.com/AmarokIce/PineappleDelight/files/14472579/crash-2024-03-03_18.11.07-server.txt)

**Comment by hanbings** [comment]
Already fix in: https://github.com/AmarokIce/PineappleDelight/pull/14
