### ISSUE TITLE
pineapple_wild_crop ResourceKey Error Cause Server Start Crash.

### ISSUE THREAD

**Issue by FelixAgairu** [AmarokIce/PineappleDelight#27]
MC 1.21.1
Fabric 0.16.9
Mod version [Pineapple Delight 1.0.3-1.21.1-Fabric](https://modrinth.com/mod/pineapple-delight/version/1.0.3-1.21.1-Fabric)

```
[main/ERROR]: Failed to start the minecraft server
java.lang.IllegalArgumentException: Couldn't find registry entry for ResourceKey[minecraft:worldgen/placed_feature / pineapple_delight:pineapple_wild_crop]
	at knot/net.fabricmc.fabric.impl.biome.modification.BiomeModificationContextImpl.getEntry(BiomeModificationContextImpl.java:340) ~[fabric-biome-api-v1-13.0.30+be1ed2d719-1e66f5f0033d03b9.jar:?]
	at knot/net.fabricmc.fabric.impl.biome.modification.BiomeModificationContextImpl$GenerationSettingsContextImpl.addFeature(BiomeModificationContextImpl.java:292) ~[fabric-biome-api-v1-13.0.30+be1ed2d719-1e66f5f0033d03b9.jar:?]
	at knot/net.fabricmc.fabric.api.biome.v1.BiomeModifications.lambda$addFeature$0(BiomeModifications.java:49) ~[fabric-biome-api-v1-13.0.30+be1ed2d719-1e66f5f0033d03b9.jar:?]
	at knot/net.fabricmc.fabric.impl.biome.modification.BiomeModificationImpl$ModifierRecord.apply(BiomeModificationImpl.java:230) ~[fabric-biome-api-v1-13.0.30+be1ed2d719-1e66f5f0033d03b9.jar:?]
	at knot/net.fabricmc.fabric.impl.biome.modification.BiomeModificationImpl.finalizeWorldGen(BiomeModificationImpl.java:152) ~[fabric-biome-api-v1-13.0.30+be1ed2d719-1e66f5f0033d03b9.jar:?]
	at knot/net.minecraft.server.MinecraftServer.handler$bee000$fabric-biome-api-v1$finalizeWorldGen(MinecraftServer.java:5626) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.<init>(MinecraftServer.java:322) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3176.<init>(class_3176.java:87) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.Main.method_29734(Main.java:246) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_29740(MinecraftServer.java:288) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.Main.main(Main.java:245) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [server.jar:1.0.1]

```

**Comment by AmarokIce** [comment]
got, thanks for report

**Comment by FelixAgairu** [comment]
i think prob already fixed, seems no issue with server and client now.

RqiuTl9x
Pineapple Delight 1.0.3-1.21.1-Fabric-Fix
